### ISSUE TITLE
Old versions of yarn break the CLI

### ISSUE THREAD

**Issue by davewasmer** [denali-js/core#438]
```
cli v0.1.2 [global]error Invalid subcommand. Try "add, bin, ls, remove, upgrade"
NestedError:
Error encountered while starting up the Denali CLI
    at Object.<anonymous> (/usr/local/lib/node_modules/@denali-js/cli/dist/bin/denali:43:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3```

**Comment by davewasmer** [comment]
Thanks to @mdbiscan for discovering this one!
